mcc -o Cw6_Standalone -m -v Cw6 AutoAdjustGain Cw6LoadSubjInfo.m Cw6_BackEnd.m Cw6_MenuFunctions.m GUIChangeDetector_callback.m ...
GetExtinctions.m SendML2Cw6.m SetLaser.m Cw6.fig loadCw6ConfigFile.m saveNIRSData.m validatesystem.m NIRS_timer_main_callback.m ...
PlotSDG.m localStopTimer.m plotmainwindow.m LaunchSplash.m LayOutFunction.m UITree_ted.m createDetTab.m createSrctab.m getjframe.m ...
uicomponent.m LoadSDG.m RegisterSubject.fig RegisterSubject.m SaveComments.m RealTimeFilterSetupMenu.fig...
RealTimeFilterSetupMenu.m processRTfunctions.m -a Splash.jpg -a cw6.cfg -d 'D:\Cw6ControlSoftware\StandAlone'