/*
 * MATLAB Compiler: 4.1 (R14SP1)
 * Date: Wed Jul 02 19:53:35 2008
 * Arguments: "-B" "macro_default" "-o" "Cw6_Standalone" "-m" "-W" "main" "-T"
 * "link:exe" "-v" "Cw6" "AutoAdjustGain" "Cw6LoadSubjInfo.m" "Cw6_BackEnd.m"
 * "Cw6_MenuFunctions.m" "GUIChangeDetector_callback.m" "GetExtinctions.m"
 * "SendML2Cw6.m" "SetLaser.m" "Cw6.fig" "loadCw6ConfigFile.m" "saveNIRSData.m"
 * "validatesystem.m" "NIRS_timer_main_callback.m" "PlotSDG.m"
 * "localStopTimer.m" "plotmainwindow.m" "LaunchSplash.m" "LayOutFunction.m"
 * "UITree_ted.m" "createDetTab.m" "createSrctab.m" "getjframe.m"
 * "uicomponent.m" "LoadSDG.m" "RegisterSubject.fig" "RegisterSubject.m"
 * "SaveComments.m" "RealTimeFilterSetupMenu.fig" "RealTimeFilterSetupMenu.m"
 * "processRTfunctions.m" "-a" "Splash.jpg" "-a" "cw6.cfg" "-d"
 * "D:\Cw6ControlSoftware\StandAlone" 
 */


#ifdef __cplusplus
extern "C" {
#endif
const unsigned char __MCC_Cw6_Standalone_public_data[] = {'3', '0', '8', '1',
                                                          '9', 'D', '3', '0',
                                                          '0', 'D', '0', '6',
                                                          '0', '9', '2', 'A',
                                                          '8', '6', '4', '8',
                                                          '8', '6', 'F', '7',
                                                          '0', 'D', '0', '1',
                                                          '0', '1', '0', '1',
                                                          '0', '5', '0', '0',
                                                          '0', '3', '8', '1',
                                                          '8', 'B', '0', '0',
                                                          '3', '0', '8', '1',
                                                          '8', '7', '0', '2',
                                                          '8', '1', '8', '1',
                                                          '0', '0', 'C', '4',
                                                          '9', 'C', 'A', 'C',
                                                          '3', '4', 'E', 'D',
                                                          '1', '3', 'A', '5',
                                                          '2', '0', '6', '5',
                                                          '8', 'F', '6', 'F',
                                                          '8', 'E', '0', '1',
                                                          '3', '8', 'C', '4',
                                                          '3', '1', '5', 'B',
                                                          '4', '3', '1', '5',
                                                          '2', '7', '7', 'E',
                                                          'D', '3', 'F', '7',
                                                          'D', 'A', 'E', '5',
                                                          '3', '0', '9', '9',
                                                          'D', 'B', '0', '8',
                                                          'E', 'E', '5', '8',
                                                          '9', 'F', '8', '0',
                                                          '4', 'D', '4', 'B',
                                                          '9', '8', '1', '3',
                                                          '2', '6', 'A', '5',
                                                          '2', 'C', 'C', 'E',
                                                          '4', '3', '8', '2',
                                                          'E', '9', 'F', '2',
                                                          'B', '4', 'D', '0',
                                                          '8', '5', 'E', 'B',
                                                          '9', '5', '0', 'C',
                                                          '7', 'A', 'B', '1',
                                                          '2', 'E', 'D', 'E',
                                                          '2', 'D', '4', '1',
                                                          '2', '9', '7', '8',
                                                          '2', '0', 'E', '6',
                                                          '3', '7', '7', 'A',
                                                          '5', 'F', 'E', 'B',
                                                          '5', '6', '8', '9',
                                                          'D', '4', 'E', '6',
                                                          '0', '3', '2', 'F',
                                                          '6', '0', 'C', '4',
                                                          '3', '0', '7', '4',
                                                          'A', '0', '4', 'C',
                                                          '2', '6', 'A', 'B',
                                                          '7', '2', 'F', '5',
                                                          '4', 'B', '5', '1',
                                                          'B', 'B', '4', '6',
                                                          '0', '5', '7', '8',
                                                          '7', '8', '5', 'B',
                                                          '1', '9', '9', '0',
                                                          '1', '4', '3', '1',
                                                          '4', 'A', '6', '5',
                                                          'F', '0', '9', '0',
                                                          'B', '6', '1', 'F',
                                                          'C', '2', '0', '1',
                                                          '6', '9', '4', '5',
                                                          '3', 'B', '5', '8',
                                                          'F', 'C', '8', 'B',
                                                          'A', '4', '3', 'E',
                                                          '6', '7', '7', '6',
                                                          'E', 'B', '7', 'E',
                                                          'C', 'D', '3', '1',
                                                          '7', '8', 'B', '5',
                                                          '6', 'A', 'B', '0',
                                                          'F', 'A', '0', '6',
                                                          'D', 'D', '6', '4',
                                                          '9', '6', '7', 'C',
                                                          'B', '1', '4', '9',
                                                          'E', '5', '0', '2',
                                                          '0', '1', '1', '1'
                                                          , '\0'};

const char *__MCC_Cw6_Standalone_name_data = "Cw6_Standalone";

const char *__MCC_Cw6_Standalone_root_data = "";

const unsigned char __MCC_Cw6_Standalone_session_data[] = {'1', 'C', '4', '0',
                                                           'E', '9', '2', '2',
                                                           'C', '8', 'A', '9',
                                                           '5', '9', '6', 'F',
                                                           '4', 'C', 'B', 'B',
                                                           '3', '6', '9', '5',
                                                           '5', '9', '4', '8',
                                                           'C', '4', '1', '3',
                                                           '0', 'F', '7', 'D',
                                                           'F', 'A', 'C', 'E',
                                                           '9', '6', '2', '7',
                                                           'B', '6', '4', '0',
                                                           '8', '0', '8', '9',
                                                           'F', '6', '3', 'D',
                                                           '9', '9', 'D', '1',
                                                           'F', '7', 'E', '8',
                                                           'C', 'D', '7', '9',
                                                           '8', '6', 'C', 'D',
                                                           'A', '5', '3', 'B',
                                                           'C', '9', '8', 'F',
                                                           'D', '2', '8', '9',
                                                           '0', '2', 'A', 'F',
                                                           'E', '8', '4', 'F',
                                                           '7', '0', '8', '8',
                                                           '8', '3', '7', '4',
                                                           '7', 'B', '8', '4',
                                                           '4', '0', '2', 'E',
                                                           'A', 'B', '1', 'D',
                                                           'B', '6', 'E', '8',
                                                           'C', '8', 'D', 'D',
                                                           'F', '7', '6', 'E',
                                                           '4', 'A', 'F', '3',
                                                           'A', 'E', 'F', '6',
                                                           'D', '8', 'B', '9',
                                                           'C', 'C', '4', 'D',
                                                           'D', 'B', '5', '4',
                                                           '1', '9', 'D', 'B',
                                                           'D', '3', '7', '0',
                                                           '9', '8', 'B', '8',
                                                           '0', '1', '7', '8',
                                                           'F', '4', '6', '3',
                                                           '4', '9', '5', '3',
                                                           '9', 'C', '3', 'F',
                                                           'B', 'F', '7', '3',
                                                           '8', 'B', '2', '8',
                                                           '4', '9', 'F', '8',
                                                           'B', '2', 'F', 'E',
                                                           '8', '7', '6', '1',
                                                           '0', '9', 'B', 'C',
                                                           'B', '4', 'B', 'E',
                                                           'B', 'D', 'F', 'B',
                                                           '7', '1', '5', '9',
                                                           'C', '8', 'C', '6',
                                                           'A', '9', '2', 'D',
                                                           '0', 'B', '6', '3',
                                                           '2', 'C', '7', '6',
                                                           'E', 'C', '3', '7',
                                                           '0', '6', '3', '0',
                                                           'A', 'D', '5', '9',
                                                           'F', 'F', 'B', '7',
                                                           '1', 'A', '3', 'B',
                                                           'E', '4', 'D', 'E',
                                                           'A', '5', '7', 'C',
                                                           '8', 'D', 'B', '7'
                                                           , '\0'};

const char *__MCC_Cw6_Standalone_matlabpath_data[] = {"Cw6_Standalone/",
                                                      "toolbox/compiler/deploy/",
                                                      "Cw6/RealTimeModules/RT_MBLL/",
                                                      "Cw6ControlSoftware/Cw6/",
                                                      "Cw6ControlSoftware/Cw6/DisplayFcn/",
                                                      "Cw6ControlSoftware/Cw6/LayOut/",
                                                      "Cw6ControlSoftware/Cw6/RegisterSubject/",
                                                      "Cw6ControlSoftware/devices/",
                                                      "$TOOLBOXMATLABDIR/general/",
                                                      "$TOOLBOXMATLABDIR/ops/",
                                                      "$TOOLBOXMATLABDIR/lang/",
                                                      "$TOOLBOXMATLABDIR/elmat/",
                                                      "$TOOLBOXMATLABDIR/elfun/",
                                                      "$TOOLBOXMATLABDIR/specfun/",
                                                      "$TOOLBOXMATLABDIR/matfun/",
                                                      "$TOOLBOXMATLABDIR/datafun/",
                                                      "$TOOLBOXMATLABDIR/polyfun/",
                                                      "$TOOLBOXMATLABDIR/funfun/",
                                                      "$TOOLBOXMATLABDIR/sparfun/",
                                                      "$TOOLBOXMATLABDIR/scribe/",
                                                      "$TOOLBOXMATLABDIR/graph2d/",
                                                      "$TOOLBOXMATLABDIR/graph3d/",
                                                      "$TOOLBOXMATLABDIR/specgraph/",
                                                      "$TOOLBOXMATLABDIR/graphics/",
                                                      "$TOOLBOXMATLABDIR/uitools/",
                                                      "$TOOLBOXMATLABDIR/strfun/",
                                                      "$TOOLBOXMATLABDIR/imagesci/",
                                                      "$TOOLBOXMATLABDIR/iofun/",
                                                      "$TOOLBOXMATLABDIR/audiovideo/",
                                                      "$TOOLBOXMATLABDIR/timefun/",
                                                      "$TOOLBOXMATLABDIR/datatypes/",
                                                      "$TOOLBOXMATLABDIR/verctrl/",
                                                      "$TOOLBOXMATLABDIR/codetools/",
                                                      "$TOOLBOXMATLABDIR/helptools/",
                                                      "$TOOLBOXMATLABDIR/winfun/",
                                                      "$TOOLBOXMATLABDIR/demos/",
                                                      "toolbox/local/",
                                                      "toolbox/stateflow/stateflow/",
                                                      "toolbox/shared/hds/",
                                                      "toolbox/compiler/",
                                                      "toolbox/control/control/",
                                                      "toolbox/control/ctrlguis/",
                                                      "toolbox/control/ctrlobsolete/",
                                                      "toolbox/control/ctrlutil/",
                                                      "toolbox/shared/controllib/",
                                                      "toolbox/shared/optimlib/",
                                                      "toolbox/database/database/",
                                                      "toolbox/ident/ident/",
                                                      "toolbox/ident/idobsolete/",
                                                      "toolbox/ident/idguis/",
                                                      "toolbox/ident/idutils/",
                                                      "toolbox/optim/",
                                                      "toolbox/robust/robust/",
                                                      "toolbox/robust/rctutil/",
                                                      "toolbox/robust/rctobsolete/robust/",
                                                      "toolbox/robust/rctobsolete/lmi/",
                                                      "toolbox/robust/rctobsolete/mutools/commands/",
                                                      "toolbox/robust/rctobsolete/mutools/subs/",
                                                      "toolbox/signal/signal/",
                                                      "toolbox/signal/sigtools/"};
const int __MCC_Cw6_Standalone_matlabpath_data_count = 60;

const char *__MCC_Cw6_Standalone_classpath_data[] = {"java/jar/toolbox/control.jar",
                                                     "java/jar/toolbox/database.jar"};
const int __MCC_Cw6_Standalone_classpath_data_count = 2;

const char *__MCC_Cw6_Standalone_mcr_application_options[] = { "" };
const int __MCC_Cw6_Standalone_mcr_application_option_count = 0;
const char *__MCC_Cw6_Standalone_mcr_runtime_options[] = { "" };
const int __MCC_Cw6_Standalone_mcr_runtime_option_count = 0;
#ifdef __cplusplus
}
#endif


